### ISSUE TITLE
Try different formatting for different purposes

### ISSUE THREAD

**Issue by ecurrencyhodler** [satsie/trybitcoin#3]
As someone going through your course, I see that both key terms and console commands are formatted in a similar way. That is slightly confusing to me. It would be much clearer if key terms were highlighted in a differently from console commands.

<img width="615" alt="Screen Shot 2022-10-07 at 4 45 39 PM" src="https://user-images.githubusercontent.com/32662508/194676532-98650fbd-b771-4e87-a54d-2e1bb7adfa67.png">

**Comment by satsie** [comment]
Totally get what you are saying here, but the point I'm trying to make is `privateKey` is a variable now, a named "thing" that the console will now recognize. If this was a real console, you could type something like `console.log(privateKey)` and it would print that long string of letters and numbers that makes up the private key. In some consoles (like a real CLI), `privateKey` would be a console command by itself. It would work just as the other things you are typing into the console.

You make a great point though that console commands, aka exactly what you need to type should be formatted differently. I can see how it would be helpful to just have a "TYPE THIS!" indicator (perhaps bold, with a different color?). Would that be a reasonable compromise?

**Comment by ecurrencyhodler** [comment]
Totally!

**Comment by satsie** [comment]
Fixed in https://github.com/satsie/trybitcoin/commit/53744b73ea0e6ad90eda7563f987130a0d4a0cc1 :rocket:
